FROM dunglas/frankenphp:php8.2

# Set the working directory
WORKDIR /app

# The application files will be mounted from the host, so we don't need to copy them.
# The user should run "composer install" on the host.
